version: "1"
rules:                      
  - base: master            
    upstream: TeamPiplup:upstream   
    mergeMethod: hardreset  
  - base: dev
    upstream: master
    conflictReviewers:
      - piplup55
conflictLabel: "conflict"