version: "1"
rules:                      
  - base: master            
    upstream: TeamPiplup:upstream   
    mergeMethod: hardreset  
    conflictReviewers:
      - piplup55
conflictLabel: "conflict"